### ISSUE TITLE
Build error in user/busybox

### ISSUE THREAD

**Issue by brantsch** [rhuitl/uClinux#2]
...
	make[4]: Entering directory '/home/coffeeholic/reverse_engineering/pollin_ip_cam/rhuitl-uclinux/user/busybox'
	Makefile:1270: *** mixed implicit and normal rules: deprecated syntax
	/home/coffeeholic/reverse_engineering/pollin_ip_cam/rhuitl-uclinux/user/busybox/Makefile:405: *** mixed implicit and normal rules: deprecated syntax
	/home/coffeeholic/reverse_engineering/pollin_ip_cam/rhuitl-uclinux/user/busybox/Makefile:1270: *** mixed implicit and normal rules: deprecated syntax
	make[5]: *** No rule to make target 'silentoldconfig'.  Stop.
	Makefile:500: recipe for target 'include/autoconf.h' failed

As you can see, `include/autoconf.h` in `user/busybox` can't be generated.
When trying to manually run `make oldconfig` in `user/busybox`, it fails too.

**Comment by rhuitl** [comment]
Didn't compile this for years... but it looks like your version of GNU Make needs changes to the Makefiles.

**Comment by brantsch** [comment]
That might very well be the case. On second thought, I might try to incorporate your changes to uClinux into a more recent version of uClinux.
I'll try that in the evening.

**Comment by brantsch** [comment]
https://github.com/Bytewerk/uClinux-ipcam
The build error in user/busybox is no longer relevant for me, as I managed to get your patched kernel to work in the most recent uClinux-dist.
