### ISSUE TITLE
binaries missing

### ISSUE THREAD

**Issue by Zibri** [rhuitl/uClinux#5]
Please release some precompiled binaries at least for arm v7

**Comment by rhuitl** [comment]
Hi @Zibri, I'm not actively maintaining this fork anymore. Also I'm not sure if it's feasible to release precompiled binaries as you usually have to customize uClinux for your target platform - there are way too many out there to support them with a single (or a few) build(s). Memory maps, MMU support, flash controllers, hardware on the SoC - it's all different and dynamic module loading is often not support or not feasible.
